# Generated by Django 4.2.16 on 2024-10-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeVilla', models.CharField(max_length=20)),
                ('prezzo_base', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prezzo_per_persona', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
