# Generated by Django 4.2.16 on 2024-11-19 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_villa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='homepage.villa')),
            ],
        ),
    ]
