# Generated by Django 4.2.16 on 2024-12-09 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0006_attivita'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='numero_persone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='prezzo_totale',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='utente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='villa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.villa'),
        ),
    ]
