# Generated by Django 4.2.16 on 2024-12-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_booking_numero_persone_booking_prezzo_totale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='numero_persone',
            field=models.PositiveIntegerField(),
        ),
    ]
