# Generated by Django 4.2.16 on 2024-12-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_booking_numero_persone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='villa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='homepage.villa'),
        ),
        migrations.CreateModel(
            name='ImmagineAttivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='attivita_pics/')),
                ('descrizione_immagine', models.CharField(blank=True, max_length=255, null=True)),
                ('attivita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='homepage.attivita')),
            ],
        ),
    ]
